#!/usr/bin/env npx tsx
/**
 * System Designer Task Runner
 * 
 * This script automates the system design workflow by:
 * 1. Scrapping the project structure
 * 2. Analyzing codebase with Explorer Agent
 * 3. Generating system design with Designer Agent
 * 
 * USAGE:
 *   npx tsx run-task.ts "<requirement>"
 * 
 * EXAMPLES:
 *   npx tsx run-task.ts "I want to add user authentication with OAuth2"
 *   npx tsx run-task.ts "Add a REST API for managing products"
 *   npx tsx run-task.ts "Implement real-time notifications with WebSockets"
 *   npx tsx run-task.ts "Create a caching layer using Redis"
 * 
 * OUTPUT:
 *   - ../project-context/context.md - Project structure and exploration results
 *   - ../project-context/ - Design documents generated by Designer Agent
 *   - /tmp/script.log - Full execution log with timestamps
 * 
 * VIEW LOGS:
 *   tail -f /tmp/script.log    # Live monitoring
 *   cat /tmp/script.log        # View all logs
 */

import { spawn, ChildProcess } from 'child_process';
import * as path from 'path';
import * as fs from 'fs';

const DEFAULT_TIMEOUT = 600;
const LOG_FILE = '/tmp/script.log';

function getTimestamp(): string {
  return new Date().toISOString();
}

function log(message: string): void {
  const timestampedMessage = `[${getTimestamp()}] ${message}`;
  console.log(message);
  try {
    fs.appendFileSync(LOG_FILE, timestampedMessage + '\n');
  } catch (err) {
    console.error(`[LOGGER] Failed to write to log file: ${err}`);
  }
}

function logError(message: string): void {
  const timestampedMessage = `[${getTimestamp()}] ${message}`;
  console.error(message);
  try {
    fs.appendFileSync(LOG_FILE, timestampedMessage + '\n');
  } catch (err) {
    console.error(`[LOGGER] Failed to write to log file: ${err}`);
  }
}

function initLogFile(): void {
  try {
    fs.writeFileSync(LOG_FILE, `=== Script started at ${getTimestamp()} ===\n`);
  } catch (err) {
    console.error(`[LOGGER] Failed to initialize log file: ${err}`);
  }
}

function runCommand(command: string, args: string[], options: { timeout?: number } = {}): Promise<number> {
  return new Promise((resolve, reject) => {
    const timeout = options.timeout || DEFAULT_TIMEOUT;
    const timeoutMs = timeout * 1000;
    
    log(`[RUN] Executing command: ${command} ${args.join(' ')}`);
    log(`[RUN] Timeout set to: ${timeout} seconds (${timeoutMs}ms)`);
    log(`[RUN] Spawning child process...`);
    
    const proc: ChildProcess = spawn(command, args, {
      stdio: 'inherit',
    });
    
    log(`[RUN] Child process spawned with PID: ${proc.pid}`);
    log(`[RUN] Waiting for process to complete...`);
    
    const timer = setTimeout(() => {
      log(`[RUN] TIMEOUT: Process exceeded ${timeout}s limit`);
      log(`[RUN] Sending SIGTERM to process ${proc.pid}`);
      proc.kill('SIGTERM');
      reject(new Error(`Command timed out after ${timeout}s`));
    }, timeoutMs);
    
    proc.on('close', (code) => {
      clearTimeout(timer);
      log(`[RUN] Process ${proc.pid} closed with exit code: ${code}`);
      if (code === 0) {
        log(`[RUN] Command completed successfully`);
        resolve(code);
      } else {
        log(`[RUN] Command failed with non-zero exit code`);
        reject(new Error(`Command exited with code ${code}`));
      }
    });
    
    proc.on('error', (err) => {
      clearTimeout(timer);
      log(`[RUN] Process error occurred: ${err.message}`);
      reject(err);
    });
  });
}

async function runScrapProject(): Promise<void> {
  log('\n========================================');
  log('=== STEP 1: Running scrap-project.ts ===');
  log('========================================');
  log('[INFO] This step will:');
  log('  - Scan the current project directory structure');
  log('  - Generate a tree representation of all files and folders');
  log('  - Create project-context/context.md with project overview');
  log('  - Prepare context for the Explorer Agent');
  log('');
  log('[INFO] Resolving script path...');
  
  const scriptPath = path.resolve(__dirname, 'scrap-project.ts');
  log(`[INFO] Script location: ${scriptPath}`);
  log('[INFO] Starting project scrap process...');
  
  await runCommand('npx', ['tsx', scriptPath]);
  
  log('\n[DONE] Project tree generated successfully');
  log('[INFO] Context file should now be available at: ../project-context/context.md\n');
}

async function callExplorerAgent(requirement: string): Promise<void> {
  log('\n========================================');
  log('=== STEP 2: Calling Explorer Agent ====');
  log('========================================');
  log('[INFO] This step will:');
  log('  - Read the generated context.md file');
  log('  - Analyze the codebase structure based on the requirement');
  log('  - Identify relevant files, modules, and components');
  log('  - Update context.md with exploration findings');
  log(`[INFO] User requirement: "${requirement}"`);
  log('');
  
  const message = `/explore ${requirement}`;
  log(`[INFO] Constructed explorer message: "${message}"`);
  log('[INFO] Invoking openclaw agent with explore agent type...');
  log(`[INFO] Agent: explore`);
  log(`[INFO] Timeout: ${DEFAULT_TIMEOUT} seconds`);
  log('');
  
  await runCommand('openclaw', [
    'agent',
    '--agent', 'explore',
    '--message', message,
    '--timeout', String(DEFAULT_TIMEOUT),
  ]);
  
  log('\n[DONE] Explorer agent completed successfully');
  log('[INFO] Context has been enriched with exploration results\n');
}

async function callDesignerAgent(requirement: string): Promise<void> {
  log('\n========================================');
  log('=== STEP 3: Calling Designer Agent ====');
  log('========================================');
  log('[INFO] This step will:');
  log('  - Read the enriched context.md from Explorer Agent');
  log('  - Analyze the requirement and existing codebase');
  log('  - Generate system design recommendations');
  log('  - Create/update design documents in project-context');
  log(`[INFO] User requirement: "${requirement}"`);
  log('');
  
  const message = `Based on the context.md in project-context folder, design a system for: ${requirement}`;
  log(`[INFO] Constructed designer message: "${message}"`);
  log('[INFO] Invoking openclaw agent with designer agent type...');
  log(`[INFO] Agent: designer`);
  log(`[INFO] Timeout: ${DEFAULT_TIMEOUT} seconds`);
  log('');
  
  await runCommand('openclaw', [
    'agent',
    '--agent', 'designer',
    '--message', message,
    '--timeout', String(DEFAULT_TIMEOUT),
  ]);
  
  log('\n[DONE] Designer agent completed successfully');
  log('[INFO] System design has been generated\n');
}

async function main(): Promise<void> {
  initLogFile();
  
  log('\n');
  log('╔══════════════════════════════════════════════════════════════╗');
  log('║           SYSTEM DESIGNER TASK RUNNER                        ║');
  log('╚══════════════════════════════════════════════════════════════╝');
  log('');
  log(`[INFO] Log file: ${LOG_FILE}`);
  log('');
  
  log('[INFO] Parsing command line arguments...');
  const args = process.argv.slice(2);
  log(`[INFO] Raw arguments received: ${args.length > 0 ? args.join(' ') : '(none)'}`);
  
  if (args.length === 0) {
    log('[ERROR] No requirement provided');
    logError('');
    logError('Usage: npx tsx run-task.ts "<requirement>"');
    logError('Example: npx tsx run-task.ts "I want to add user authentication with OAuth2"');
    process.exit(1);
  }
  
  const requirement = args.join(' ');
  
  log('');
  log('========================================');
  log('TASK CONFIGURATION');
  log('========================================');
  log(`Requirement: ${requirement}`);
  log(`Default Timeout: ${DEFAULT_TIMEOUT} seconds`);
  log(`Working Directory: ${__dirname}`);
  log('========================================');
  log('');
  log('[INFO] The following steps will be executed:');
  log('  1. Scrap Project - Generate project structure');
  log('  2. Explorer Agent - Analyze codebase for requirement');
  log('  3. Designer Agent - Create system design');
  log('');
  log('[INFO] Starting task execution...\n');
  
  try {
    log('[INFO] Executing STEP 1 of 3...');
    await runScrapProject();
    log('[INFO] STEP 1 completed successfully\n');
    
    log('[INFO] Executing STEP 2 of 3...');
    await callExplorerAgent(requirement);
    log('[INFO] STEP 2 completed successfully\n');
    
    log('[INFO] Executing STEP 3 of 3...');
    await callDesignerAgent(requirement);
    log('[INFO] STEP 3 completed successfully\n');
    
    log('[INFO] Cleaning up context.md...');
    const contextFilePath = path.resolve(__dirname, '../project-context/context.md');
    try {
      fs.unlinkSync(contextFilePath);
      log('[INFO] context.md deleted successfully\n');
    } catch (err) {
      log(`[WARN] Failed to delete context.md: ${err}\n`);
    }
    
    log('\n');
    log('╔══════════════════════════════════════════════════════════════╗');
    log('║          ALL TASKS COMPLETED SUCCESSFULLY                    ║');
    log('╚══════════════════════════════════════════════════════════════╝');
    log('');
    log('[INFO] Summary:');
    log('  - Project structure has been scrapped');
    log('  - Codebase has been explored based on requirement');
    log('  - System design has been generated');
    log('');
    log('[INFO] Check ../project-context/ for output files');
    log(`[INFO] Full log available at: ${LOG_FILE}`);
    log('');
    
  } catch (error) {
    log('');
    log('╔══════════════════════════════════════════════════════════════╗');
    log('║                    TASK FAILED                               ║');
    log('╚══════════════════════════════════════════════════════════════╝');
    log('');
    logError(`[ERROR] ${error instanceof Error ? error.message : error}`);
    if (error instanceof Error && error.stack) {
      logError(`[ERROR] Stack trace: ${error.stack}`);
    }
    process.exit(1);
  }
}

main();
